name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v3
      with: # should match .sdkmanrc
        distribution: temurin
        java-version: 17.0.8
        cache: sbt

    - name: Compile
      run: sbt compile

    - name: Run tests
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: sbt clean coverage test && sbt coverageAggregate
        coverageLocations: ${{github.workspace}}/target/**/coverage-report/cobertura.xml:cobertura
