name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Scala & sbt
      uses: sdkman/sdkman-action@b1f9b69
      id: sdkman

    - name: Compile
      run: sbt compile

    - name: Run tests
      run: sbt test