name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v3
      with: # should match .sdkmanrc
        distribution: temurin
        java-version: 17.0.8.1
        cache: sbt

    - name: Compile
      run: sbt compile

    - name: Run tests
      run: sbt clean test
